name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Deploy only when pushing to main branch

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build & Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/healthy-highway-426311-i0/my-repo/my-app .
        docker push us-central1-docker.pkg.dev/healthy-highway-426311-i0/my-repo/my-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-app \
          --image=us-central1-docker.pkg.dev/healthy-highway-426311-i0/my-repo/my-app \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
